name: Bug Report
description: Report a Bug
title: "[BUG]: "
labels: ["Remote Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating this issue, please tell us more about the problem.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What browser did you use when you had the bug?
      options:
        - Firefox
        - Firefox Developer Edition
        - Safari
        - Chrome
        - Chromium
        - Opera
        - Opera GX
        - Microsoft Edge
        - Internet Explorer
        - QQ Browser
        - elinks
        - Samsung Internet
        - Vivaldi
        - Brave
        - Other (Tell us the name the name in the box below)
    validations:
      required: true
  - type: textarea
    id: other-browser
    attributes:
      label: Tell us the name the name of your browser if you select Other
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us the name
    validations:
      required: false
  - type: dropdown
    id: OS
    attributes:
      label: Tell on what OS do you see the bug
      multiple: true
      options:
        - MacOS
        - iOS
        - Android
        - WatchOS
        - ChromeOS
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
