name: HTML5 & CSS Validator
# Github Actions sintaxis help:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

#Based on: https://github.com/marketplace/actions/html5-validator

on:
  pull_request: {}
  push:
    branches: ["main"]
jobs:
  validate:
    name: Validate HTML5 & CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          css: true
          format: text
