# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PHP Runner

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install dependencies
      run: |
        sudo apt-get install libapache2-mod-php5 install php5-common install php5-cli
        apt list --installed

# -Name: PHP Runner
#  run: |
# php PHP_Ghost_Simulator.php
