name: PHP Composer

on:

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: HTML Preview
    id: html_preview
    uses: pavi2410/html-preview-action@v2
    with:
      html_file: 'PHP_Ghost_Simulator.php'
