name: Check PHP syntax

on:
  pull_request: {}
  push:
    branches: ["main"]

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check PHP syntax
        uses: pipeline-components/php-codesniffer@v0.12.3
